serverlessworkflow/sdk-java

api/src/main/resources/schema/default/defaultdef.json, api/src/main/resources/schema/states/switchstate.json, api/src/main/resources/schema/switchconditions/datacondition.json, api/src/main/resources/schema/switchconditions/eventcondition.json, api/src/test/resources/examples/applicantrequest.json, api/src/test/resources/examples/applicantrequest.yml, api/src/test/resources/examples/creditcheck.json, api/src/test/resources/examples/creditcheck.yml, api/src/test/resources/examples/eventbasedtransition.json, api/src/test/resources/examples/eventbasedtransition.yml, api/src/test/resources/examples/jobmonitoring.json, api/src/test/resources/examples/jobmonitoring.yml
update to switch state default param and conditions
=> Update to switch state conditions and default param

api/src/main/java/io/serverlessworkflow/api/interfaces/State.java, api/src/main/resources/schema/end/end.json, api/src/main/resources/schema/states/callbackstate.json, api/src/main/resources/schema/states/defaultstate.json, api/src/main/resources/schema/states/delaystate.json, api/src/main/resources/schema/states/foreachstate.json, api/src/main/resources/schema/states/injectstate.json, api/src/main/resources/schema/states/operationstate.json, api/src/main/resources/schema/states/parallelstate.json, api/src/main/resources/schema/states/subflowstate.json, api/src/main/resources/schema/states/switchstate.json, api/src/main/resources/schema/transitions/transition.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/compensationworkflow.json, api/src/test/resources/features/compensationworkflow.yml
=> [1.0.x] Workflow compensation impl

api/pom.xml, pom.xml, validation/pom.xml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
In this PR, we remove the need to have the JitPack repository declared in our POM. Some companies do not allow adding or using libraries that are not uploaded to Maven Central. It can be a problem for our community. More Info: https://github.com/everit-org/json-schema/issues/360 
The JSON Schema library is exclusively distributed via JitPack, but they also upload to Maven Central under a different artifact and group id. Although it can take some time after the initial release, it's worth not to depend on third-party repositories.
```xml
<dependency>
<groupId>com.github.erosb</groupId> …
```
=> Removing dependency from JitPack repository

README.md
I forgot to remove this line from the README. We don't need that anymore.
=> Removing JitPack repo from the doc

api/src/main/resources/schema/cron/crondef.json, api/src/main/resources/schema/schedule/schedule.json, api/src/test/resources/examples/periodicinboxcheck.json, api/src/test/resources/examples/periodicinboxcheck.yml, diagram/src/test/resources/examples/periodicinboxcheck.json, diagram/src/test/resources/examples/periodicinboxcheck.yml
=> update to schedule def cron

api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionDefinitionTypeDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/resources/schema/functions/functiondef.json, api/src/main/resources/schema/transitions/transition.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/functiontypes.json, api/src/test/resources/features/functiontypes.yml
=> update to function definition types

api/pom.xml, pom.xml, validation/pom.xml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
Since the most used log framework is slf4j, and we are using it in our project, it doesn't make sense to bring another logging framework to our dependency list. One of our dependencies uses `commons-logging`. I just replaced it with a bridge to slf4j. So now, everything is logged using the same framework.
=> Replacing commons-logging with slf4j in transitive dependencies

README.md, api/src/main/java/io/serverlessworkflow/api/interfaces/WorkflowDiagram.java, diagram/src/main/java/io/serverlessworkflow/diagram/WorkflowDiagramImpl.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/WorkflowDiagramModel.java, diagram/src/main/java/io/serverlessworkflow/diagram/utils/WorkflowToPlantuml.java, diagram/src/main/resources/templates/plantuml/workflow-template.txt
=> disable diagram legend by default

api/src/test/resources/examples/booklending.json, api/src/test/resources/examples/booklending.yml, diagram/src/test/resources/examples/booklending.json, diagram/src/test/resources/examples/booklending.yml
=> Fix ISO 8601 format

diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelConnection.java
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Fixes opt.semgrep.java.lang.correctness.no-string-eqeq.no-string-eqeq : Strings should not be compared with '=='. This is a reference comparison operator. Use '.equals()' instead.
=> (bugsbash)fixes strings should not be compared with '=='

.muse.toml
Signed-off-by: janaganh <janagan.h@gmail.com>
**What this PR does / why we need it**: Adding muse dev config to ignore generated 2 java files from json
=> Adding muse dev config to ignore generated 2 java files from json  - BugBash

validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> improve validation

api/src/main/resources/schema/states/parallelstate.json, api/src/test/resources/examples/parallel.json, api/src/test/resources/examples/parallel.yml, diagram/src/test/resources/examples/parallel.json, diagram/src/test/resources/examples/parallel.yml
=> update to completion type

api/src/main/resources/schema/actions/action.json, api/src/main/resources/schema/sleep/sleep.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/actionssleep.json, api/src/test/resources/features/actionssleep.yml
=> Add actions sleep

api/src/main/resources/schema/states/foreachstate.json
=> update foreach state

api/src/main/java/io/serverlessworkflow/api/deserializers/ErrorsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/java/io/serverlessworkflow/api/workflow/Errors.java, api/src/main/resources/schema/actions/action.json, api/src/main/resources/schema/error/error.json, api/src/main/resources/schema/error/errordef.json, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/examples/jobmonitoring.json, api/src/test/resources/examples/jobmonitoring.yml, api/src/test/resources/examples/provisionorder.json, api/src/test/resources/examples/provisionorder.yml, api/src/test/resources/features/errors.json, api/src/test/resources/features/errors.yml, api/src/test/resources/features/retriesprops.json, api/src/test/resources/features/retriesprops.yml, api/src/test/resources/features/vetappointment.json, api/src/test/resources/features/vetappointment.yml, diagram/src/test/resources/examples/jobmonitoring.json, diagram/src/test/resources/examples/jobmonitoring.yml, diagram/src/test/resources/examples/provisionorder.json, diagram/src/test/resources/examples/provisionorder.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java
=> Update error handling and retries

api/src/main/java/io/serverlessworkflow/api/deserializers/ContinueAsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/EndDefinitionDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/ContinueAsSerializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/EndDefinitionSerializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/StateExecTimeoutSerializer.java, api/src/main/resources/schema/end/continueas.json, api/src/main/resources/schema/end/end.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/continueasobject.json, api/src/test/resources/features/continueasobject.yml, api/src/test/resources/features/continueasstring.json, api/src/test/resources/features/continueasstring.yml
=> adding continueas

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> Update poms for local release

README.md, utils/src/test/java/io/serverlessworkflow/util/EventsTest.java
Signed-off-by: manick02 <manickavasagam.sundaram@gmail.com>
This PR updates README for the usage of workflow utils
=> Updated README.md for Utils #127

README.md, api/src/main/java/io/serverlessworkflow/api/interfaces/WorkflowDiagram.java, diagram/src/main/java/io/serverlessworkflow/diagram/WorkflowDiagramImpl.java, diagram/src/main/java/io/serverlessworkflow/diagram/utils/WorkflowToPlantuml.java, diagram/src/test/java/io/serverlessworkflow/diagram/test/CustomTemplateWorkflowDiagramTest.java, diagram/src/test/resources/templates/plantuml/custom-template.txt
Signed-off-by: Maciej Swiderski <swiderski.maciej@gmail.com>
allows to use custom template for generating diagrams
=> allow to use custom workflow template for generatig diagrams

diagram/src/test/java/io/serverlessworkflow/diagram/test/CustomTemplateWorkflowDiagramTest.java, diagram/src/test/resources/templates/plantuml/custom-template.txt
=> small test change for diagram template

.github/workflows/maven-deploy.yml, .github/workflows/maven-verify.yml, api/pom.xml, pom.xml
- Java **8** is quite old
- Let's update the project with **Java 11** version
- Updated all pom.xml to use placeholder
- Updated also github workflow
Here is my output on my laptop
> [INFO] Serverless Workflow :: Parent ...................... SUCCESS [  0.277 s]
[INFO] Serverless Workflow :: API ......................... SUCCESS [ 11.516 s]
[INFO] Serverless Workflow :: SPI ......................... SUCCESS [  1.466 s]
[INFO] Serverless Workflow :: Validation .................. SUCCESS [  2.439 s]
[INFO] Serverless Workflow :: Diagram ..................... SUCCESS [ 11.380 s]
[INFO] Serverless Workflow :: Utils …
=> Update to Java 11

api/src/main/java/io/serverlessworkflow/api/deserializers/AuthDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/java/io/serverlessworkflow/api/workflow/Auth.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/java/io/serverlessworkflow/api/test/WorkflowToMarkupTest.java, api/src/test/resources/features/authbasic.json, api/src/test/resources/features/authbasic.yml, api/src/test/resources/features/authbearer.json, api/src/test/resources/features/authbearer.yml, api/src/test/resources/features/authoauth.json, api/src/test/resources/features/authoauth.yml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
Per the spec, the [Auth](https://github.com/serverlessworkflow/specification/blob/main/schema/auth.json#L14) property is an array, not an object. This makes sense since a workflow could have multiple functions accessing different openapi spec files over other servers with varying auth schemes.
The `*Deseralizer` classes look pretty much the same. I believe we can improve this one in the future.
Perhaps timeouts should be done the same thing, but I'll open a different PR.
=> Auth Workflow attribute supposed to be an array

validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
Fixes issue with validation for callback state function ref
=> fix validation for callback state

api/src/main/java/io/serverlessworkflow/api/deserializers/AuthDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/java/io/serverlessworkflow/api/workflow/Auth.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/java/io/serverlessworkflow/api/test/WorkflowToMarkupTest.java, api/src/test/resources/features/authbasic.json, api/src/test/resources/features/authbasic.yml, api/src/test/resources/features/authbearer.json, api/src/test/resources/features/authbearer.yml, api/src/test/resources/features/authoauth.json, api/src/test/resources/features/authoauth.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> [4.0.x] latest updates from main

api/src/main/java/io/serverlessworkflow/api/deserializers/ConstantsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/java/io/serverlessworkflow/api/test/WorkflowToMarkupTest.java, api/src/test/resources/features/constantsRef.json, api/src/test/resources/features/constantsRef.yml
Setting the ref value when constant is an uri to allow implementations
to try load them in case default loading fails
=> Constanst.setRefValue() was always null

api_rest/mvnw, api_rest/mvnw.cmd, api_rest/pom.xml, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/Application.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/ControllerErrorException.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/IRouterRest.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/RouterPaths.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/RouterRest.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/ServerlesRequestHelper.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/ServerlessRequest.java, api_rest/src/main/java/io/serverlessworkflow/reactive_api_rest/ServerlessWorkFlowResponse.java, api_rest/src/main/resources/application.yml, api_rest/src/main/resources/templates/plantuml/custom-template.txt, api_rest/src/test/java/io/serverlessworkflow/reactive_api_rest/ServerlesRequestHelperTest.java, pom.xml
Signed-off-by: davideduma <david24eduma@gmail.com>
**:heart:**
**What this PR does / why we need it**:  Reactive api rest for get SVG
=> Enhancement. Reactive api rest for get SVG #216

api/pom.xml, api/src/test/java/io/serverlessworkflow/api/test/CodegenTest.java, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java
Fixes https://github.com/serverlessworkflow/sdk-java/issues/204.
Changes:
* Set [initializeCollections](https://joelittlejohn.github.io/jsonschema2pojo/site/1.1.2/generate-mojo.html#initializeCollections) jsonschema2pojo property to `false`
* Added test
* Fixed test that started to fail after setting `initializeCollections` to `false`
=> Change to not initialize collections by default on generated POJOs

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java
Before the PR, the file resulting of executing this code
```
Workflow workflow = new Workflow("HelloWorld", "Hello World", "1.0", Arrays.asList(
new InjectState(START_STATE, Type.INJECT).withData(new ObjectMapper().createObjectNode().put("response","Hello World!!!")).withEnd(new End())))
.withStart(new Start().withStateName(START_STATE));
try (Writer writer = new FileWriter("helloworld.json")) {
new JsonObjectMapper().writeValue(writer, workflow);
} catch (IOException io) {
throw new UncheckedIOException(io);
}
```
was 
```
{
"id" : "HelloWorld",
"name" : "HelloWorld",
"version" : "1_0",
"start" : "inject_0",
"expressionLang" : "jq",
"events" : [ ],
"functions" : [ ],
"retries" : [ ],
"errors" : [ ],
"secrets" : [ ],
"states" : [ {
"data" : {
"response" : "Hello World!!!"
}, …
```
=> Make serialized workflow compatible with schema

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/applicantrequest-with-id-and-key.json, api/src/test/resources/features/applicantrequest-with-id-and-key.yml, api/src/test/resources/features/applicantrequest-with-key.json, api/src/test/resources/features/applicantrequest-with-key.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> [4.0.x] Key property is missing in the Workflow

.github/dependabot.yml
We can rely on GitHub's dependabot to open PRs with version upgrades and CVEs fixes to avoid future problems.
=> Enable dependabot to upgrade libs

api/src/main/resources/schema/produce/produceevent.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/transitions.json, api/src/test/resources/features/transitions.yml
**What this PR does / why we need it**: 
The ProduceEvent Definition [here](https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#producedevent-definition) has this concept of contextAttributes but in the SDK, the POJO does not have it ([ref](https://github.com/serverlessworkflow/sdk-java/blob/dc1a9dc48d75764fcd16a51c60f06f0718a3696e/api/src/main/resources/schema/produce/produceevent.json#L4)). Which causes exception at the time of converting String to Workflow POJO.
This PR attempts to fix that.
N/A
N/A
=> add missing support for contextAttributes in ProduceEvent

api/src/main/java/io/serverlessworkflow/api/workflow/Events.java
It makes the Events class Serialiazable. Other classes are already implementing this interface so making this one consistent with others. 
Corresponding discussion on Slack: https://cloud-native.slack.com/archives/CMBAZQSEP/p1692019690656669
=> Make Events class Serializable

api/src/main/resources/schema/workflow.json, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
This makes id mandatory, keeping current constructor unchanged from the previous version
SDK has currently two misaligments with the spec: id and name are mandatory, while the former is mandatory only if there is no key and the latter is optional. Since making id optionally depending on key is not a good idea that will be probably changed in 0.9 (where ID will be mandatory always and key removed or make optional), I think is better to postpone the API breaking change to the migration to 0.9
=> Force id to be mandatory

.github/project.yml, README.md
The GPG keys can't be shared in a branch from a fork, we must run the action against a branch in the main repo. That's why I'm opening the PR, to try to run the release workflow correctly this time.
In #273, the branch is from my personal fork, hence the secrets were not shared in the action run: https://github.com/serverlessworkflow/sdk-java/actions/runs/6720556047/job/18264384738
=> Prepare 4.0.5.1 release

.github/project.yml, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
Another try to release 4.0.5.
The `pom.xml` file should have the `-SNAPSHOT` suffix, the maven release and javadoc plugin were missing the version numbers.
Release was approved in #273
=> Fix 4.0.x branch to enable release 4.0.5

.github/workflows/release.yml, pom.xml
In this PR, we again continue our endeavor to fix the pipeline to release in one click. I was missing a few actions in the release step to create a new branch to perform the release from there.
=> Fix release pipeline to checkout before performing release

.github/project.yml
PR to trigger the 4.0.5.Final release on branch 4.0.x
- Tag the release from 4.0.x branch
- Release in Maven central
Release already approved in #273
=> Relase 4.0.5.Final

api/src/main/java/io/serverlessworkflow/api/workflow/Auth.java, api/src/main/java/io/serverlessworkflow/api/workflow/Constants.java, api/src/main/java/io/serverlessworkflow/api/workflow/DataInputSchema.java, api/src/main/java/io/serverlessworkflow/api/workflow/Errors.java, api/src/main/java/io/serverlessworkflow/api/workflow/Functions.java, api/src/main/java/io/serverlessworkflow/api/workflow/Retries.java, api/src/main/java/io/serverlessworkflow/api/workflow/Secrets.java
There were some manually created POJOs which did not implement serializable interface. Making those implement Serializable interface here. This will enable Workflow objects transferrable over wire.
=> Make classes serializable

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
Fixes #213 
I've also removed a few deprecated usages (see put/set) and simplified a few methods in the class I was working on.
=> Fix #213 - Make  a required property for Retry and verify RetryDef

validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> Fix #232 - Add Errors validation to skipMessages

validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> Fix #357 - Add OAuth Validation Test

api/src/main/resources/schema/workflow.yaml, custom-generator/src/main/java/io/serverlessworkflow/generator/EmptyObjectTypeRule.java
Some generated classes are empty and not really used
=> Removing empty classes

api/src/main/java/io/serverlessworkflow/api/OneOfValueProvider.java, api/src/test/java/io/serverlessworkflow/api/ApiTest.java, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java, custom-generator/src/main/java/io/serverlessworkflow/generator/GeneratorUtils.java
Any**Many thanks for submitting your Pull Request :heart:!**
I was using the library and it felt a by unconfortable to check every item on an oneOf if it was null or not to define it inner type so i made a minor tweak on generator and deserializers to haver a hint allowing the use of a switch expression to select the type.
Here follows a example of usage:
```java
switch (taskitem.get()) {
case CallTask callTask -> {
switch (callTask.get()) {
case CallHTTP httpCall -> {
yield activities.execute(HTTP_ACTION_METHOD_NAME, TaskResult.class, execution.getContext(), input);
}
case CallGRPC grpcCall -> {
throw new NotImplementedException();
}
case CallFunction functionCall -> {
throw new NotImplementedException();
}
case CallOpenAPI openApiCall -> {
throw …
```
=> Add helper function to facilitate use of library with oneOf types

.github/project.yml
We have to keep the `snapshot` suffix to the version.
=> [Fix][Add snapshot] Prepare Release 7.0.0-alpha1

api/src/test/java/io/serverlessworkflow/api/FeaturesTest.java, api/src/test/resources/features/listen.yaml, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java, custom-generator/src/main/java/io/serverlessworkflow/generator/GeneratorUtils.java, custom-generator/src/main/java/io/serverlessworkflow/generator/UnevaluatedPropertiesRule.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/412
=> Fix #412 Adding OneOf support to EventConsumptionStrategy

api/pom.xml, api/src/main/java/io/serverlessworkflow/api/ObjectMapperFactory.java, api/src/main/java/io/serverlessworkflow/serialization/BeanDeserializerModifierWithValidation.java, api/src/main/java/io/serverlessworkflow/serialization/BeanDeserializerWithValidation.java, api/src/main/java/io/serverlessworkflow/serialization/DeserializeHelper.java, api/src/test/java/io/serverlessworkflow/api/ApiTest.java, api/src/test/java/io/serverlessworkflow/api/FeaturesTest.java, api/src/test/resources/features/callFunction.yaml, api/src/test/resources/features/callHttp.yaml, api/src/test/resources/features/callOpenAPI.yaml, api/src/test/resources/features/composite.yaml, api/src/test/resources/features/data-flow.yaml, api/src/test/resources/features/emit.yaml, api/src/test/resources/features/flow.yaml, api/src/test/resources/features/for.yaml, api/src/test/resources/features/listen.yaml, api/src/test/resources/features/raise.yaml, api/src/test/resources/features/set.yaml, api/src/test/resources/features/switch.yaml, api/src/test/resources/features/try.yaml, custom-generator/src/main/java/io/serverlessworkflow/generator/ConstAnnotator.java, pom.xml
Fix https://github.com/serverlessworkflow/sdk-java/issues/418
=> [Fix #418] Adding const support

api/src/main/java/io/serverlessworkflow/serialization/SerializeHelper.java
After addiction of `OneOfValuePRovider` interface, we can remove reflection usage for serialization, which was causing issues as reported [here](https://github.com/serverlessworkflow/sdk-java/pull/428)
=> Use OneOfValueProvider for serialization

api/src/main/java/io/serverlessworkflow/api/ObjectMapperFactory.java, api/src/main/java/io/serverlessworkflow/serialization/URIDeserializer.java, api/src/main/java/io/serverlessworkflow/serialization/URISerializer.java, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java, impl/src/main/java/io/serverlessworkflow/impl/DefaultTaskExecutorFactory.java, impl/src/main/java/io/serverlessworkflow/impl/HttpExecutor.java, impl/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/src/main/resources/callHttp.yaml, impl/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/449
=> [Fix_#449] Checking pattern

api/src/main/java/io/serverlessworkflow/api/OneOfValueProvider.java, api/src/main/java/io/serverlessworkflow/api/WorkflowReader.java, api/src/main/java/io/serverlessworkflow/api/WorkflowWriter.java, api/src/main/java/io/serverlessworkflow/serialization/DeserializeHelper.java, api/src/main/java/io/serverlessworkflow/serialization/OneOfSetter.java, api/src/test/java/io/serverlessworkflow/api/FeaturesTest.java, api/src/test/resources/features/authentication-bearer-uri-format.yaml, api/src/test/resources/features/authentication-bearer.yaml, api/src/test/resources/features/authentication-oauth2-secret.yaml, api/src/test/resources/features/authentication-oauth2.yaml, api/src/test/resources/features/authentication-oidc-secret.yaml, api/src/test/resources/features/authentication-oidc.yaml, api/src/test/resources/features/authentication-reusable.yaml, api/src/test/resources/features/call-http-query-parameters.yaml, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java, custom-generator/src/main/java/io/serverlessworkflow/generator/GeneratorUtils.java, custom-generator/src/main/java/io/serverlessworkflow/generator/UnevaluatedPropertiesRule.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/461
This slightly change the generated code public API. 
Properties in POJOs that contains both properties and oneOf are moved to a parent class which is inherited by the oneOf alternative classes. This is done that way because reading two nested classes from the same json node is pretty tricky and will move the complexity to the generated serializer/deserializer (reinventing Jackson essentially) 
Just one example, previously we have 
```
public class Schema implements Serializable, OneOfValueProvider
{
/**
* SchemaFormat
* <p>
* The schema's format. Defaults to 'json'. The (optional) version of the format can be set using `{format}:{version}`.
* 
*/
@JsonProperty("format")
@JsonPropertyDescription("The schema's format. Defaults to …
```
=> [Fix #461] oneOf options must inherit union class common part

impl/pom.xml, impl/src/main/java/io/serverlessworkflow/impl/WorkflowContext.java, impl/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/src/main/java/io/serverlessworkflow/impl/WorkflowFactories.java, impl/src/main/java/io/serverlessworkflow/impl/WorkflowFilter.java, impl/src/main/java/io/serverlessworkflow/impl/WorkflowUtils.java, impl/src/main/java/io/serverlessworkflow/impl/executors/AbstractTaskExecutor.java, impl/src/main/java/io/serverlessworkflow/impl/executors/DefaultTaskExecutorFactory.java, impl/src/main/java/io/serverlessworkflow/impl/executors/HttpExecutor.java, impl/src/main/java/io/serverlessworkflow/impl/expressions/Expression.java, impl/src/main/java/io/serverlessworkflow/impl/expressions/ExpressionUtils.java, impl/src/main/java/io/serverlessworkflow/impl/expressions/JQExpression.java, impl/src/main/java/io/serverlessworkflow/impl/jsonschema/DefaultSchemaValidator.java, impl/src/main/java/io/serverlessworkflow/impl/jsonschema/DefaultSchemaValidatorFactory.java, impl/src/main/java/io/serverlessworkflow/impl/jsonschema/SchemaValidator.java, impl/src/main/java/io/serverlessworkflow/impl/jsonschema/SchemaValidatorFactory.java, impl/src/main/java/io/serverlessworkflow/resources/ClasspathResource.java, impl/src/main/java/io/serverlessworkflow/resources/DefaultResourceLoader.java, impl/src/main/java/io/serverlessworkflow/resources/DefaultResourceLoaderFactory.java, impl/src/main/java/io/serverlessworkflow/resources/DynamicResource.java, impl/src/main/java/io/serverlessworkflow/resources/FileResource.java, impl/src/main/java/io/serverlessworkflow/resources/HttpResource.java, impl/src/main/java/io/serverlessworkflow/resources/ResourceLoader.java, impl/src/main/java/io/serverlessworkflow/resources/ResourceLoaderFactory.java, impl/src/main/java/io/serverlessworkflow/resources/StaticResource.java, impl/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/src/test/resources/call-http-query-parameters-external-schema.yaml, impl/src/test/resources/schema/searchquery.yaml
Fix https://github.com/serverlessworkflow/sdk-java/issues/467
=> [Fix #467]  Adding schema validation

impl/core/src/main/java/io/serverlessworkflow/impl/ContextAware.java, impl/core/src/main/java/io/serverlessworkflow/impl/DefaultWorkflowPosition.java, impl/core/src/main/java/io/serverlessworkflow/impl/DefaultWorkflowPositionFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/TaskContext.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowApplication.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowContext.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowFilter.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowPosition.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowPositionFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowUtils.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/AbstractTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/DefaultTaskExecutorFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/DoExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ForExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/SetExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/SwitchExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/TaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/ExpressionUtils.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/JQExpression.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/core/src/test/resources/for-collect.yaml, impl/core/src/test/resources/for-sum.yaml, impl/http/src/main/java/io/serverlessworkflow/impl/executors/HttpExecutor.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/474
=> [Fix_#474] For task implementation

api/src/main/resources/schema/workflow.yaml, impl/core/src/main/java/io/serverlessworkflow/impl/StringFilter.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowError.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowException.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowUtils.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/DefaultTaskExecutorFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/DoExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ForExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/RaiseExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/TryExecutor.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/core/src/test/resources/raise-inline copy.yaml, impl/core/src/test/resources/raise-reusable.yaml, impl/http/src/main/java/io/serverlessworkflow/impl/executors/HttpExecutor.java, impl/http/src/test/java/io/serverlessworkflow/impl/HTTPWorkflowDefinitionTest.java, impl/http/src/test/resources/callGetHttp.yaml
Fix https://github.com/serverlessworkflow/sdk-java/issues/468
=> [Fix #468] Try/raise implementation

.github/project.yml
Release alpha 5.1
See blog https://github.com/serverlessworkflow/serverlessworkflow.github.io/pull/218
=> Release alpha5.1

impl/http/src/test/java/io/serverlessworkflow/impl/HTTPWorkflowDefinitionTest.java, impl/http/src/test/resources/call-http-query-parameters-external-schema.yaml, impl/http/src/test/resources/call-http-query-parameters.yaml, impl/http/src/test/resources/schema/searchquery.yaml
=> Star Wars api is down

impl/http/src/test/java/io/serverlessworkflow/impl/HTTPWorkflowDefinitionTest.java, impl/http/src/test/resources/call-http-endpoint-interpolation.yaml
The pet API might randomly return a 404.
=> Fix http flaky test

impl/core/src/main/java/io/serverlessworkflow/impl/executors/SetExecutor.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/core/src/test/resources/for-collect.yaml, impl/core/src/test/resources/for-sum.yaml, impl/core/src/test/resources/switch-then-string.yaml
Fix https://github.com/apache/incubator-kie-kogito-apps/pull/2166
=> [Fix #500] Fixing set behaviour

api/src/main/java/io/serverlessworkflow/api/WorkflowReader.java, api/src/test/java/io/serverlessworkflow/api/FeaturesTest.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/506
=> [Fix #506] Change order of parameters in WorkflowReader

impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowInstance.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/http/src/test/java/io/serverlessworkflow/impl/HTTPWorkflowDefinitionTest.java
Differentiated between Pending and Started cases, being more adapted to the spec.
=> Api start changes

api/src/main/resources/schema/workflow.yaml, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/514
=> [Fix_#514] Ignore nodes that only has required

impl/core/src/main/java/io/serverlessworkflow/impl/executors/ListenExecutor.java, impl/core/src/test/java/io/serverlessworkflow/impl/EventDefinitionTest.java, impl/core/src/test/resources/listen-to-all.yaml
=> Adding listen to all test

README.md, examples/events/pom.xml, examples/events/src/main/java/events/EventExample.java, examples/events/src/main/resources/emit.yaml, examples/events/src/main/resources/listen.yaml, examples/pom.xml, examples/simpleGet/pom.xml, examples/simpleGet/src/main/java/io/serverlessworkflow/impl/BlockingExample.java, examples/simpleGet/src/main/java/io/serverlessworkflow/impl/NotBlockingExample.java, examples/simpleGet/src/main/resources/get.yaml, impl/README.md, impl/core/src/main/java/io/serverlessworkflow/impl/DefaultExecutorServiceFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowApplication.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/events/InMemoryEvents.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ListenExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/TaskExecutorHelper.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/WaitExecutor.java, impl/core/src/test/java/io/serverlessworkflow/impl/EventDefinitionTest.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/HttpExecutor.java, impl/pom.xml, pom.xml
Updated readme before first release of the reference implementation
=> [Fix #520] Updating readme

.github/project.yml, .github/workflows/pre-release.yml, README.md, impl/README.md
=> Release 7.0.0.Final

.github/workflows/release.yml
=> Remove nexus plugin steps

impl/core/src/main/java/io/serverlessworkflow/impl/executors/AbstractTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/RegularTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/SwitchExecutor.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/core/src/test/resources/conditional-set.yaml
Fix https://github.com/serverlessworkflow/sdk-java/issues/549
=> [Fix_#549] Implement if for all task

api/src/main/resources/schema/produce/produceevent.json
Fix https://github.com/serverlessworkflow/sdk-java/issues/558
=> [Fix #558] ProduceEvent.data shoud be an object, not only a string

api/src/main/resources/schema/events/eventref.json
=> [Fix #558] Update event ref

experimental/lambda/src/main/java/io/serverlessworkflow/impl/expressions/JavaModel.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/expressions/JavaModelCollection.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/expressions/JavaModelFactory.java
When using a map, not JavaModel should be returned as value. 
JavaModel should not be visible to final user.
=> Ensure not workflowmodel is returned within a Map or Collection

examples/pom.xml, examples/simpleGet/pom.xml, impl/http/pom.xml, impl/pom.xml
Avoid direct dependency of HTTP module with Jersey. 
User will have to add a valid Jakarta RS implementation in the pom
=> Http dependencies

experimental/lambda/src/test/java/io/serverless/workflow/impl/FluentDSLCallTest.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/DelegatingFuncDoTaskFluent.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncCallTaskBuilder.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncDoTaskBuilder.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncDoTaskFluent.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncForkTaskBuilder.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncTaskItemListBuilder.java, fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncWorkflowBuilder.java, fluent/func/src/test/java/io/serverlessworkflow/fluent/func/JavaWorkflowBuilderTest.java, fluent/pom.xml, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/BaseDoTaskBuilder.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/BaseTaskItemListBuilder.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/DelegatingDoTaskFluent.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/DoTaskFluent.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/HasDelegate.java, fluent/spec/src/test/java/io/serverlessworkflow/fluent/spec/WorkflowBuilderTest.java, pom.xml
Quick refactor to make the DSL more extensible for the `agentic` module in the other PR.
I split the changes there in this PR so we can safely merge it to continue improving the Java DSL.
=> Improvements on the DSL to make it more extensible

.github/workflows/maven-verify.yml, fluent/agentic/pom.xml, fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentAdapters.java, fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentDoTaskBuilder.java, fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentTaskItemListBuilder.java, fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentWorkflowBuilder.java, fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/LoopAgentsBuilder.java, fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/spi/AgentDoFluent.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentTaskItemListBuilderTest.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentWorkflowBuilderTest.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/Agents.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentsUtils.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/Models.java, fluent/pom.xml
=> Introduce Fluent Agent DSL (depends on LangChain4j SNAPSHOT)

experimental/lambda-fluent/pom.xml, experimental/lambda/pom.xml, experimental/pom.xml, experimental/types/pom.xml, fluent/README.md, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentDslWorkflowTest.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentWorkflowBuilderTest.java
Added a few more unit tests for `agentic` and proper documentation for the new `fluent` module. Introduced the new `serverlessworkflow-lambda-fluent` module to bring in Fluent + Java impl in a single dependency.
=> Add more unit tests and docs for fluent

.github/workflows/maven-verify.yml
Temporary skip to have a green CI again. We will revert as soon as we get a LC4j snaphsot available.
=> Skiping Agentic modules

impl/core/src/main/java/io/serverlessworkflow/impl/TaskContext.java, impl/core/src/main/java/io/serverlessworkflow/impl/TaskContextData.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowMutableInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowStatus.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/AbstractTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ListenExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/WaitExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/WorkflowErrorCEData.java, impl/jackson/src/test/java/io/serverlessworkflow/impl/LifeCycleEventsTest.java, impl/jackson/src/test/resources/wait-set.yaml
Fix https://github.com/serverlessworkflow/sdk-java/issues/695
=> [Fix #695] Suspending/cancelling/resume

experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaFuncUtils.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaListenExecutorBuilder.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaTaskExecutorFactory.java, experimental/types/src/main/java/io/serverlessworkflow/api/types/func/UntilPredicate.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ListenExecutor.java, impl/jackson/src/test/java/io/serverlessworkflow/impl/LifeCycleEventsTest.java
Adding Java predicate to Listen until
=> Add Until listen predicate

fluent/agentic-langchain4j/src/main/java/io/serverlessworkflow/fluent/agentic/langchain4j/ParallelAgentServiceImpl.java, impl/core/src/main/java/io/serverlessworkflow/impl/AbstractExecutorServiceHolder.java, impl/core/src/main/java/io/serverlessworkflow/impl/DefaultExecutorServiceFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/ExecutorServiceHolder.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowApplication.java, impl/core/src/main/java/io/serverlessworkflow/impl/events/EventConsumer.java, impl/core/src/main/java/io/serverlessworkflow/impl/events/EventPublisher.java, impl/core/src/main/java/io/serverlessworkflow/impl/events/InMemoryEvents.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/722
=> [Fix #722] Close executor service if created

api/src/test/java/io/serverlessworkflow/api/ApiTest.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/OAuth2AuthenticationPolicyBuilder.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/OIDCBuilder.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/oauth/ClientSecretBasic.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/oauth/ClientSecretPostStep.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/oauth/HttpRequestBuilder.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/oauth/OAuthRequestBuilder.java, types/src/main/resources/schema/workflow.yaml
=> fix typo: Autenthication -> to -> Authentication

impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowMutableInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/AbstractLifeCyclePublisher.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/TaskCancelledCEData.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/TaskResumedCEData.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/TaskSuspendedCEData.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/WorkflowCancelledCEData.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/WorkflowResumedCEData.java, impl/core/src/main/java/io/serverlessworkflow/impl/lifecycle/ce/WorkflowSuspendedCEData.java, impl/jackson/src/main/java/io/serverlessworkflow/impl/jackson/events/JacksonLifeCyclePublisher.java, impl/test/src/test/java/io/serverlessworkflow/impl/test/LifeCycleEventsTest.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/704
=> [Fix #704] Adding CloudEvents for Workflow suspended and resumed

fluent/agentic-langchain4j/src/main/java/io/serverlessworkflow/fluent/agentic/langchain4j/AbstractAgentService.java, fluent/agentic-langchain4j/src/main/java/io/serverlessworkflow/fluent/agentic/langchain4j/ParallelAgentServiceImpl.java, fluent/agentic-langchain4j/src/main/java/io/serverlessworkflow/fluent/agentic/langchain4j/WorkflowInvocationHandler.java, fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/WorkflowTests.java, pom.xml
Fixes:
1. https://github.com/serverlessworkflow/sdk-java/pull/756
2. https://github.com/serverlessworkflow/sdk-java/pull/752
=> chore: Bump jackson-annotations and lc4j.beta

experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentWorkflowBuilder.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/configurer/AgentTaskConfigurer.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/configurer/FuncPredicateEventConfigurer.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/configurer/ListenConfigurer.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/configurer/SwitchCaseConfigurer.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/dsl/AgenticDSL.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/dsl/ListenSpec.java, experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/dsl/SwitchCaseSpec.java, experimental/fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentDslWorkflowTest.java, experimental/fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/EmailDrafterIT.java, experimental/fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/MixedWorkflowIT.java, experimental/fluent/func/src/main/java/io/serverlessworkflow/fluent/func/FuncSwitchTaskBuilder.java, fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/BaseWorkflowBuilder.java
Fix #732 
This is not the end yet; we can progress as we receive feedback from the community to improve the DSL as we go. But it sets the basis for the next iterations.
=> Fix #732 - Add static imports and consumer recipes for Agentic DSL

experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/dsl/AgenticDSL.java
It would be nice to have AgentTaskConfigurer conditional(Predicate<?> predicate, Object agent)  in the AgenticDSL
=> add helper conditional to the AgenticDSL class

impl/jackson/src/main/java/io/serverlessworkflow/impl/expressions/jq/JQExpressionFactory.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/819
=> [Fix #819] Allow passing scope supplier to JQExpression constructor

experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaConsumerCallExecutor.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaForExecutorBuilder.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaFunctionCallExecutor.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaListenExecutorBuilder.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaLoopFunctionCallExecutor.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaLoopFunctionIndexCallExecutor.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaSwitchExecutorBuilder.java, experimental/lambda/src/main/java/io/serverlessworkflow/impl/executors/func/JavaTaskExecutorFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/AbstractTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/CallTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/CallableTask.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/DefaultTaskExecutorFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/DoExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/EmitExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ForExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ForkExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/ListenExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/RaiseExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/RegularTaskExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/SetExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/SwitchExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/TaskExecutorFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/TaskExecutorHelper.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/TryExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/WaitExecutor.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/HttpExecutor.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/822
=> [Fix #822] TaskExecutorFactory to accept WorkflowDefinition

experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentTaskItemListBuilder.java, experimental/fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentDslWorkflowTest.java, experimental/fluent/agentic/src/test/java/io/serverlessworkflow/fluent/agentic/AgentsUtils.java
I propose changing the branch naming when executing agentic parallel tasks.
Since the agent’s name will be used (or the method name if the agent’s name is not specified), the naming of execution results in the context will be strictly deterministic, which will significantly simplify further work with the results.
Drawbacks: if multiple instances of the same agent with identical names are used in a parallel task, the results of the later executions will overwrite the results of the earlier ones.
=> use agent name as branch name
