serverlessworkflow/sdk-java

MAINTAINERS.md, maintainer_guidelines.md
=> Adding maintainers and maitainers guidelines

README.md
=> Small fixes to readme

api/src/main/resources/schema/retry/retry.json, api/src/main/resources/schema/states/parallelstate.json
=> Spec alignment - integer type props

api/src/main/resources/schema/end/end.json, api/src/main/resources/schema/transitions/transition.json, api/src/test/resources/examples/sendcloudevent.json, api/src/test/resources/examples/sendcloudevent.yml
aligns the sdk with updates to specification - transition and end definition produceEvents
=> Updating spec to latest - produceEvents def

api/src/main/java/io/serverlessworkflow/api/deserializers/EventsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/java/io/serverlessworkflow/api/utils/Utils.java, api/src/main/java/io/serverlessworkflow/api/workflow/Events.java, api/src/main/java/io/serverlessworkflow/api/workflow/Functions.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/java/io/serverlessworkflow/api/test/WorkflowToMarkupTest.java, api/src/test/resources/features/applicantrequest.json, api/src/test/resources/features/applicantrequest.yml, api/src/test/resources/features/applicantrequestfunctions.json, api/src/test/resources/features/applicantrequestfunctions.yml, api/src/test/resources/features/vetappointment.json, api/src/test/resources/features/vetappointment.yml, api/src/test/resources/features/vetappointmenteventrefs.json, api/src/test/resources/features/vetappointmenteventrefs.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java
Adds ability to do function and event file reference (from classpath). This aligns the function and event definitions with specification.
=> Functions and event definitions reference capability

README.md
=> Adding Grade projects instructions

README.md
=> Fix api examples in readme

README.md
=> Readme update for function def changes

api/src/main/resources/schema/retry/retry.json
=> adding jitter to retry def

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> bumping version to 1.0.0-SNAPSHOT

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> bumping version

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> bumping version to 2.0.0-SNAPSHOT

README.md
=> update readme - add release link

.github/workflows/maven-deploy.yml, .github/workflows/maven-verify.yml
=> update maven actions - adding 1.0.x branch

pom.xml
=> update to pom for release info

.github/workflows/maven-deploy.yml, .github/workflows/maven-verify.yml
=> update branches for actions

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> fixing pom for release - version bump

README.md
=> bumping latest release version

api/src/main/java/io/serverlessworkflow/api/interfaces/State.java, api/src/main/resources/schema/end/end.json, api/src/main/resources/schema/states/callbackstate.json, api/src/main/resources/schema/states/defaultstate.json, api/src/main/resources/schema/states/delaystate.json, api/src/main/resources/schema/states/foreachstate.json, api/src/main/resources/schema/states/injectstate.json, api/src/main/resources/schema/states/operationstate.json, api/src/main/resources/schema/states/parallelstate.json, api/src/main/resources/schema/states/subflowstate.json, api/src/main/resources/schema/states/switchstate.json, api/src/main/resources/schema/transitions/transition.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/compensationworkflow.json, api/src/test/resources/features/compensationworkflow.yml
=> Workflow compensation impl

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> [1.0.x] Bumping version to 1.0.2.Final

README.md
=> updating release table

README.md
=> [1.0.x] fix link in release table

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> 1.0.3 release update

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> setting 1.0.x branch version

README.md
=> update releases table

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/exectimeout/exectimeout.json, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/examples/roomreadings.json, api/src/test/resources/examples/roomreadings.yml, api/src/test/resources/features/keepactiveexectimeout.json, api/src/test/resources/features/keepactiveexectimeout.yml
=> add workflow exectimeout and keepactive

api/src/main/java/io/serverlessworkflow/api/interfaces/State.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/states/defaultstate.json, api/src/main/resources/schema/workflow.json
=> removing data schema props

api/src/main/resources/schema/repeat/repeat.json, api/src/main/resources/schema/states/subflowstate.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/examples/checkcarvitals.json, api/src/test/resources/examples/checkcarvitals.yml, api/src/test/resources/features/checkcarvitals.json, api/src/test/resources/features/checkcarvitals.yml
=> add switch state repeat

api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionRefDeserializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/FunctionRefSerializer.java, api/src/main/resources/schema/functions/functionref.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/functionrefjsonparams.json, api/src/test/resources/features/functionrefjsonparams.yml, api/src/test/resources/features/functionrefnoparams.json, api/src/test/resources/features/functionrefnoparams.yml
=> update functionref params to jsonnode

api/src/main/resources/schema/functions/functiondef.json
=> Add grpc function def

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> [2.0.x] 2.0.x branch prepare

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> 2.0.0.Final relase updates

README.md
=> update readme for 2.0.0.Final release

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> Update 2.0.x branch

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> Update to 3.0.0-SNAPSHOT

.github/workflows/maven-deploy.yml, .github/workflows/maven-verify.yml
=> fix workflow actions

diagram/src/main/java/io/serverlessworkflow/diagram/WorkflowDiagramImpl.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelConnection.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelState.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelStateDef.java, diagram/src/main/java/io/serverlessworkflow/diagram/utils/WorkflowDiagramUtils.java, diagram/src/test/java/io/serverlessworkflow/diagram/test/WorkflowDiagramTest.java
=> Fixing issue with diagram generation with state names with spaces

diagram/src/main/java/io/serverlessworkflow/diagram/model/WorkflowDiagramModel.java
Signed-off-by: Tihomir Surdilovic <tsurdilovic@tihomirs-mbp.attlocal.net>
=> Fix default action mode for diagram

maintainer_guidelines.md
=> fix main branch name

api/src/main/resources/schema/retry/retrydef.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/retriesprops.json, api/src/test/resources/features/retriesprops.yml
=> Fix retries properties

api/src/main/java/io/serverlessworkflow/api/deserializers/DataInputSchemaDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/datainputschema/datainputschema.json, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/datainputschemaobj.json, api/src/test/resources/features/datainputschemaobj.yml, api/src/test/resources/features/datainputschemastring.json, api/src/test/resources/features/datainputschemastring.yml
=> Adding workflow dataInputSchema property

api/src/test/resources/examples/jobmonitoring.json
=> fix small typo

api/src/main/java/io/serverlessworkflow/api/schemaclient/ResourceSchemaClient.java
**What this PR does / why we need it**: Fixed Missing Override 
=> Fixed Missing Override - BugBash

api/src/main/java/io/serverlessworkflow/api/deserializers/CronDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionRefDeserializer.java
**What this PR does / why we need it**: removed unused local variable ObjectMapper
=> Removed Unused Local variable ObjectMapper - BugBash

api/src/main/java/io/serverlessworkflow/api/deserializers/ScheduleDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/StartDefinitionDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/TransitionDeserializer.java, diagram/src/main/java/io/serverlessworkflow/diagram/WorkflowDiagramImpl.java
**What this PR does / why we need it**: Removed unused logger fields
=> Removed unused logger fields - BugBash

diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelStateDef.java, diagram/src/main/java/io/serverlessworkflow/diagram/utils/WorkflowDiagramUtils.java
**What this PR does / why we need it**: changed StringBuffer to StringBuilder
=> changed StringBuffer to StringBuilder - BugBash

diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelConnection.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelState.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/WorkflowDiagramModel.java
**What this PR does / why we need it**: changed StringBuffer to StringBuilder
=> changed StringBuffer to StringBuilder  - BugBash

validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java
**What this PR does / why we need it**:Fixed unchecked warning
**Special notes for reviewers**:NA
**Additional information (if needed):**NA
=> Fixed unchecked warning - BugBash

api/src/main/java/io/serverlessworkflow/api/mapper/BaseObjectMapper.java, api/src/main/java/io/serverlessworkflow/api/mapper/YamlObjectMapper.java
Signed-off-by: janaganh <janagan.h@gmail.com>
**What this PR does / why we need it**: Fixed parentheses warning 
=> Fixed parentheses warning - BugBash

api/src/main/java/io/serverlessworkflow/api/utils/Utils.java
Signed-off-by: janaganh <janagan.h@gmail.com>
**What this PR does / why we need it**: Suppressed defaultcharset warning 
=> Suppressed defaultcharset warning - BugBash

api/src/main/java/io/serverlessworkflow/api/deserializers/CronDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/EndDefinitionDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/EventsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionRefDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/RetriesDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/ScheduleDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/StartDefinitionDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/TransitionDeserializer.java, api/src/main/java/io/serverlessworkflow/api/schemaclient/ResourceSchemaClient.java, diagram/src/main/java/io/serverlessworkflow/diagram/WorkflowDiagramImpl.java, diagram/src/main/java/io/serverlessworkflow/diagram/model/ModelState.java
Signed-off-by: janaganh <janagan.h@gmail.com>
**What this PR does / why we need it**:Suppressed unused variable warning
**Special notes for reviewers**:NA
=> Suppressed unused variable warning - BugBash

api/src/main/resources/schema/defaultcondition/defaultconditiondef.json, api/src/main/resources/schema/states/switchstate.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/examples/applicantrequest.json, api/src/test/resources/examples/applicantrequest.yml, api/src/test/resources/examples/checkcarvitals.json, api/src/test/resources/examples/checkcarvitals.yml, api/src/test/resources/examples/creditcheck.json, api/src/test/resources/examples/creditcheck.yml, api/src/test/resources/examples/eventbasedtransition.json, api/src/test/resources/examples/eventbasedtransition.yml, api/src/test/resources/examples/jobmonitoring.json, api/src/test/resources/examples/jobmonitoring.yml, api/src/test/resources/features/applicantrequest.json, api/src/test/resources/features/applicantrequest.yml, api/src/test/resources/features/transitions.json, api/src/test/resources/features/transitions.yml, diagram/src/main/java/io/serverlessworkflow/diagram/model/WorkflowDiagramModel.java, diagram/src/test/resources/examples/applicantrequest.json, diagram/src/test/resources/examples/applicantrequest.yml, diagram/src/test/resources/examples/checkcarvitals.json, diagram/src/test/resources/examples/checkcarvitals.yml, diagram/src/test/resources/examples/creditcheck.json, diagram/src/test/resources/examples/creditcheck.yml, diagram/src/test/resources/examples/eventbasedtransition.json, diagram/src/test/resources/examples/eventbasedtransition.yml, diagram/src/test/resources/examples/jobmonitoring.json, diagram/src/test/resources/examples/jobmonitoring.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java
=> update to switch state default condition

api/src/main/resources/schema/branches/branch.json, api/src/main/resources/schema/states/foreachstate.json, api/src/test/resources/examples/parallel.json, api/src/test/resources/examples/parallel.yml, diagram/src/main/java/io/serverlessworkflow/diagram/model/WorkflowDiagramModel.java, diagram/src/test/resources/examples/parallel.json, diagram/src/test/resources/examples/parallel.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> remove workflowid from parallel and foreach states

api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionRefDeserializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/FunctionRefSerializer.java, api/src/main/resources/schema/functions/functiondef.json, api/src/main/resources/schema/functions/functionref.json
=> add graphql supp

api/src/main/java/io/serverlessworkflow/api/deserializers/ConstantsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/SecretsDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/java/io/serverlessworkflow/api/workflow/Constants.java, api/src/main/java/io/serverlessworkflow/api/workflow/Secrets.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/constants.json, api/src/test/resources/features/constants.yml, api/src/test/resources/features/secrets.json, api/src/test/resources/features/secrets.yml
=> adding secrets and constants

api/src/main/java/io/serverlessworkflow/api/deserializers/StateExecTimeoutDeserializer.java, api/src/main/java/io/serverlessworkflow/api/mapper/WorkflowModule.java, api/src/main/java/io/serverlessworkflow/api/serializers/StateExecTimeoutSerializer.java, api/src/main/resources/schema/timeouts/stateexectimeout.json, api/src/main/resources/schema/timeouts/timeoutsdef.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java
=> Updating state exec timeout

api/src/main/java/io/serverlessworkflow/api/deserializers/SubFlowRefDeserializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/SubFlowRefSerializer.java, api/src/main/resources/schema/functions/subflowref.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/checkcarvitals.json, api/src/test/resources/features/checkcarvitals.yml, api/src/test/resources/features/subflowref.json, api/src/test/resources/features/subflowref.yml
=> Removing waitForCompletion for subflowref

api/src/main/resources/schema/functions/functiondef.json
=> adding odata function type support

api/src/main/resources/schema/functions/functiondef.json
=> adding asyncapi to function defs

README.md
=> [0.3.x] update readme for 0.3.x

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> fixing poms for branch

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, validation/pom.xml
=> update main branch to 4.0.0-SNAPSHOT

README.md, utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java
Changed field to final in WorkflowUtils
Signed-off-by: cb-manick <80755357+cb-manick@users.noreply.github.com>
Update of read me for Util module
Update of field to final 
=> Update Readme with usage of util dependency  #127

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/GetStatesTest.java, utils/src/test/resources/getStates/workflowwithstates.yml
Signed-off-by: manick02 <manickavasagam.sundaram@gmail.com>
Signed-off-by: cb-manick <80755357+cb-manick@users.noreply.github.com>
=> Implement GetStates by StateType utility method #127

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/FunctionDefinitionsTest.java
Signed-off-by: manick02 <manickavasagam.sundaram@gmail.com>
Implemented GetActionForFunctionDefinition utility Method
=> Implemented GetActionsForFunctionDefinition #127

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/GetNumTests.java
Implement numOfStates and numOfStates by stateType
=> Implement numOfStates and numOfStates by stateType #127

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/GetNumTests.java
=> Added GetNum of EndState utility method #127

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java
Considered SwitchState in getNumOfEndState util method
Bug fix
=> Considered SwitchState in getNumOfEndState util method

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java
Signed-off-by: manick02 <manickavasagam.sundaram@gmail.com>
One last fix GetNumOfEndStates util method to take care of SwitchState  #127
=> Last bugfix GetNumOfEndStates util method to take care of SwitchState  #127

api/src/main/resources/schema/functions/functiondef.json
=> adding 'custom' function type

api/src/main/resources/schema/events/eventref.json
=> adding result event timeout to eventref

api/src/main/resources/schema/actions/action.json
=> Adding action id prop

api/src/main/java/io/serverlessworkflow/api/deserializers/FunctionRefDeserializer.java, api/src/main/java/io/serverlessworkflow/api/deserializers/SubFlowRefDeserializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/FunctionRefSerializer.java, api/src/main/java/io/serverlessworkflow/api/serializers/SubFlowRefSerializer.java, api/src/main/resources/schema/events/eventref.json, api/src/main/resources/schema/functions/functionref.json, api/src/main/resources/schema/functions/subflowref.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/invoke.json, api/src/test/resources/features/invoke.yml
=> adding async function invoke

api/src/main/java/io/serverlessworkflow/api/serializers/SubFlowRefSerializer.java
=> fix subflow ref serializer

api/src/main/resources/schema/filters/actiondatafilter.json, api/src/main/resources/schema/filters/eventdatafilter.json
=> update data filter props

api/src/main/resources/schema/actions/action.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/errors.json, api/src/test/resources/features/errors.yml
=> adding condition to actions

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/GetStatesTest.java
=> adding getStateWithName util method

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/JsonManipulationTest.java
=> adding some json manipulation util methods

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> updates for 4.0 final

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> change version to 4.0.x

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> update version to 5.0.0-SNAPSHOT

validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
Validation fixes to match specification Version0.8 - iterationParam, workflow startState, and workflow name are made optional
=> Validation fixes to match Specification V0.8

validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> small formatting for validator test

validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> fix small spelling

validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
=> small formatting fix

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/FunctionsWithTypeTest.java, utils/src/test/resources/functiontypes/workflowfunctiontypes.yml
=> Add getFunctionDefinitionsWithType to workflow utils

utils/src/main/java/io/serverlessworkflow/utils/WorkflowUtils.java, utils/src/test/java/io/serverlessworkflow/util/FunctionDefinitionsTest.java, utils/src/test/resources/functiontypes/workflowfunctiontypes.yml
=> Add getFunctionDefinitionWithName to workflow utils

pom.xml
=> adding jar plugin

api/pom.xml, pom.xml
=> fixing jar plugin

api/pom.xml, pom.xml
=> update jar plugin

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> 4.0.1.Final release

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> update to 4.0.x

README.md
=> Update readme to latest release

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/annotations.json, api/src/test/resources/features/annotations.yml
=> Adding support for annotations prop

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/annotations.json, api/src/test/resources/features/annotations.yml
=> [4.0.x] Adding support for annotations prop

README.md, api/src/main/java/io/serverlessworkflow/api/interfaces/WorkflowDiagram.java, diagram/src/main/java/io/serverlessworkflow/diagram/WorkflowDiagramImpl.java, diagram/src/main/java/io/serverlessworkflow/diagram/utils/WorkflowToPlantuml.java, diagram/src/test/java/io/serverlessworkflow/diagram/test/CustomTemplateWorkflowDiagramTest.java, diagram/src/test/resources/templates/plantuml/custom-template.txt
Signed-off-by: Maciej Swiderski <swiderski.maciej@gmail.com>
=> allow to use custom workflow template for generatig diagrams

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> [4.0.x] 4.0.2.Final release setup

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> [4.0.x] update 4.0.x

README.md
=> update readmen for 4.0.2.Final release

README.md
Signed-off-by: gautric <gautric@redhat.com>
Update the readme to include mapping SDK-Java version vs. JDK version
Enjoy...
=> add sdk-jdk mapping into doc

api/src/main/resources/schema/events/eventdef.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/eventdefdataonly.json, api/src/test/resources/features/eventdefdataonly.yml
Adds dataOnly prop to eventDef
=> Add missing dataOnly prop to eventDef

api/src/main/resources/schema/events/eventdef.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/eventdefdataonly.json, api/src/test/resources/features/eventdefdataonly.yml
=> [4.0.x] Add missing dataOnly prop to eventDef

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> Update poms for 4.0.3.Final release

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> reset version to 4.0.x

pom.xml
Fix Vulnerability in everit-json
=> Fix Vulnerability in everit-json

README.md
Small change to fix the links with the correct versions in the README.
=> Fixing release version links

.github/CODEOWNERS, .github/OWNERS, MAINTAINERS.md
=> Add Manick to maintainers and code reviewers docs

diagram-rest/src/test/java/io/serverlessworkflow/diagramrest/DiagramGenerationTest.java
=> small refactor for diagram rest api test class

diagram-rest/.gitignore
=> add gitignore

.gitignore, pom.xml
Fix #229 
Once we merge this, I'll cherry-pick it together with #193.
As a side-effect of releasing 4.0.4 we fix #192 
=> Fix #229 - Fix CVE-2017-5929, CVE-2020-15250, and CVE-2022-45688

.gitignore, pom.xml
Cherry pick for:
- #229 
- #193
As soon as we merge this, we can release 4.0.4
=> Cherry-pick CVEs fixes and javadoc upgrade

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java
Cherry-pick for #224 
@tsurdilo looks like this one is also a critical for 4.x.
=> Make serialized workflow compatible with schema (#224)

api/src/main/java/io/serverlessworkflow/api/serializers/WorkflowSerializer.java, api/src/main/resources/schema/workflow.json, api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java, api/src/test/resources/features/applicantrequest-with-id-and-key.json, api/src/test/resources/features/applicantrequest-with-id-and-key.yml, api/src/test/resources/features/applicantrequest-with-key.json, api/src/test/resources/features/applicantrequest-with-key.yml, validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
fixes https://github.com/serverlessworkflow/sdk-java/issues/227
=> Key property is missing in the Workflow

README.md, api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
just prep for next release (poms)
=> prep for 4.0.4 release

api/pom.xml, diagram/pom.xml, pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> switch back to 4.0.x

README.md
adds 4.0.4.Final release to readme
=> add 4.0.4.Final release

api/pom.xml, diagram/pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> Remove unnecessary version tags from pom.xml files

api/pom.xml, diagram/pom.xml, spi/pom.xml, utils/pom.xml, validation/pom.xml
=> [4.0.x] Remove unnecessary version tags from pom.xml files

api/src/main/java/io/serverlessworkflow/api/workflow/Events.java, pom.xml, validation/src/test/java/io/serverlessworkflow/validation/test/WorkflowValidationTest.java
Fix the bump registered in #324 
The library changed the message output, so our tests won't pass.
=> Upgrade com.networknt:json-schema-validator from 1.1.0 to 1.3.2

.github/workflows/release.yml, api/src/main/java/io/serverlessworkflow/api/workflow/Events.java, pom.xml
In this PR, we align the main branch with the changes made in 4.0.x to release 4.0.5.
N/A
N/A
=> Fix pom plugins and release GHA to match with 4.0.x branch

api/src/main/resources/schema/states/switchstate.json
Fixes https://github.com/serverlessworkflow/sdk-java/issues/333
=> [Fix #333] Fixing typo in defaultcondition

README.md
Quick update on README file for the upcoming newly 5.0.0 version.
=> Update README.md to reflect the upcoming 5.0.0 version

.github/CODEOWNERS, .github/OWNERS, MAINTAINERS.md
Based on the current project status, we are reviewing maintainers of subprojects based on their current commitment to this community. 
@cdavernas please review this PR and approve if you think this makes sense.
@manick02 is still a maintainer and we value their contribution to reviewing code and eventual contributions based on his past commitment and recent contributions. We will keep reviewing community engagement to stop spamming contributors with GH notifications to review PRs or causing other members to wait too long to move on.
=> NO-ISSUE: Review maintainers and codeowners

custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java
=> Using Linkedhashset for deterministic generation

api/src/main/resources/schema/workflow.yaml
=> Updating schema for release

.github/project.yml
Preparation for the next release based on Spec 1.0.0
=> Prepare release 7.0.0-alpha1

.github/project.yml
Failed to update the meta information in #404, so I'm opening a new one.
=> [Fix] Prepare Release 7.0.0-alpha1

.github/CODEOWNERS, .github/OWNERS, MAINTAINERS.md
In this PR, we propose adding @fjtirado to the maintainer's list due to his past contributions and leading the implementation of the new Specification DSL version. He plans to continue working and maintaining this code base with me.
@manick02 @cdavernas, please vote. Based on our [governance model](https://github.com/serverlessworkflow/specification/blob/main/GOVERNANCE.md#conflict-resolution), you have two days, or the lazy consensus will be considered, and I will merge this PR.
As a follow-up to merge the PR, I'll add @fjtirado to this repo's admin list.
=> Add fjtirado to the maintainers list

api/src/main/resources/schema/workflow.yaml, api/src/test/java/io/serverlessworkflow/api/ApiTest.java, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/444
=> [Fix #444] Wrapper class for anyOf containing strings

.github/project.yml
=> Release 7.0.0-alpha5

custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java
=> Fix schema union not generated for input/output

.github/workflows/maven-verify.yml, .github/workflows/release.yml
Reaction to https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Migration to v4 actions

impl/core/pom.xml, impl/core/src/main/java/io/serverlessworkflow/impl/QueueWorkflowPosition.java, impl/core/src/main/java/io/serverlessworkflow/impl/RuntimeDescriptorFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/StringBufferWorkflowPosition.java, impl/core/src/main/java/io/serverlessworkflow/impl/TaskContext.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowApplication.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowDefinition.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowIdFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowInstance.java, impl/core/src/main/java/io/serverlessworkflow/impl/WorkflowPositionFactory.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/DateTimeDescriptor.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/JQExpression.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/RuntimeDescriptor.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/TaskDescriptor.java, impl/core/src/main/java/io/serverlessworkflow/impl/expressions/WorkflowDescriptor.java, impl/core/src/test/java/io/serverlessworkflow/impl/WorkflowDefinitionTest.java, impl/core/src/test/resources/simple-expression.yaml
Fix https://github.com/serverlessworkflow/sdk-java/issues/463
=> [Fix #463] Supporting runtime expressions

examples/events/pom.xml, examples/simpleGet/pom.xml, pom.xml
=> Examples artifacts should not be uploaded

impl/http/pom.xml, impl/http/src/test/java/io/serverlessworkflow/impl/HTTPWorkflowDefinitionTest.java, impl/http/src/test/resources/callPostHttp.yaml
Changed swagger API to Fakerestapi for POST testing purposing. The former one was flaky
=> Fixing tests problems with swagger pet api and post call

api/pom.xml
=> [Fix #543] Not compiled dependencies should be runtime

api/src/main/resources/schema/workflow.yaml, custom-generator/src/main/java/io/serverlessworkflow/generator/AllAnyOneOfSchemaRule.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/RaiseExecutor.java, impl/core/src/main/java/io/serverlessworkflow/impl/executors/SetExecutor.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/HttpExecutor.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/555
=> [Fix_#555] New inheritance approach in schema

.github/project.yml
Include these schema changes (not backward compatible)
- https://github.com/serverlessworkflow/specification/issues/1087
- https://github.com/serverlessworkflow/specification/issues/1076
- https://github.com/serverlessworkflow/specification/issues/1079
=> Release 7.1.0.Final

pom.xml
See https://github.com/serverlessworkflow/sdk-java/pull/583
=> [main] Upgrade Jackson to 2.19.0

.github/project.yml
=> Release 5.2.0.Final

.github/project.yml
=> Release 4.3.0.Final

generators/jackson/src/main/java/io/serverlessworkflow/generator/jackson/JacksonMixInPojo.java
=> Fixing maven plugin prefix

impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/OAuth2AuthProvider.java, impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/oauth/AccessTokenProvider.java, impl/jwt-impl/pom.xml, impl/jwt-impl/src/main/java/io/serverlessworkflow/impl/http/jwt/JacksonJWTConverter.java, impl/jwt-impl/src/main/java/io/serverlessworkflow/impl/http/jwt/JacksonJWTImpl.java, impl/jwt-impl/src/test/java/io/serverlessworkflow/impl/http/jwt/JacksonJWTImplTest.java, impl/jwt/src/main/java/io/serverlessworkflow/http/jwt/JWT.java
=> Better JWT token processing

.gitattributes, impl/test/src/test/java/io/serverlessworkflow/impl/test/LifeCycleEventsTest.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/742
=> [Fix #742] Relaxing event date test condition

experimental/fluent/agentic/src/main/java/io/serverlessworkflow/fluent/agentic/AgentTaskItemListBuilder.java
=> update in accordance with the 1.6.0-beta12 version of langchain4j

.github/project.yml
Releasing a patch version.
- From the parsing/rendering objects no critical changes
- From impl a few bugs fixed
- Agentic has upgrades to catch up upstream/a few bugs fixed
- DSL has a few more breaking changes on experimental.
We will be iterating weekly from now on. Minor releases only if the impl changes.
=> Release 7.2.1.Final
